version: "3"

services:
  rabbit:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  microservicoa:
    build:
      context: a/.
      dockerfile: Dockerfile
    container_name: "service_a"
    image: "cicerorod/microservico-avancadev-a:latest"
    ports:
      - 9090:9090
    depends_on:
      - rabbit

  microservicob:
    build:
      context: b/.
      dockerfile: Dockerfile
    container_name: "service_b"
    image: "cicerorod/microservico-avancadev-b:latest"
    ports:
      - 9091:9091
    depends_on:
      - rabbit

  microservicoc:
    build:
      context: c/.
      dockerfile: Dockerfile
    container_name: "service_c"
    image: "cicerorod/microservico-avancadev-c:latest"
    ports:
      - 9092:9092
    depends_on:
      - rabbit
